-- Active: 1777536934072@@127.0.0.1@3306@portfolio
CREATE TABLE users (
    id BIGINT AUTO_INCREMENT PRIMARY KEY, -- ID
    name VARCHAR(50) NOT NULL, -- ユーザー名
    email VARCHAR(255) NOT NULL UNIQUE, -- ログインID
    password VARCHAR(255) NOT NULL, -- パスワード
    role ENUM('USER', 'ADMIN') NOT NULL DEFAULT 'USER', -- ユーザー権限
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, -- 登録日時
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, -- 更新日時
    deleted TINYINT(1) NOT NULL DEFAULT 0 -- 削除フラグ
);